"""Shared deterministic checks for the Agent Plugins Author skill."""

from __future__ import annotations

import hashlib
import json
import os
import re
from pathlib import Path
from typing import Any, Iterable


PORTABLE_SCHEMA = "https://agent-plugins.org/schemas/1.0.0/plugin.schema.json"
MCP_SCHEMA = "https://agent-plugins.org/schemas/1.0.0/mcp.schema.json"
NAME_PATTERN = re.compile(r"^(?!.*(?:--|\.\.))[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?$")
FRONTMATTER_NAME_PATTERN = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
FORBIDDEN_PORTABLE_FIELDS = {"skills", "apps", "mcpServers", "hooks"}
PORTABLE_FIELDS = {
    "$schema",
    "name",
    "version",
    "description",
    "author",
    "homepage",
    "repository",
    "license",
    "keywords",
    "extensions",
}
SECRET_FILENAME_PARTS = {
    ".env",
    "credentials",
    "credential",
    "secrets",
    "secret",
    "id_rsa",
    "id_ed25519",
}
SECRET_SUFFIXES = {".pem", ".key", ".p12", ".pfx", ".crt"}
SECRET_VALUE_PATTERNS = (
    re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----"),
    re.compile(r"\b(?:ghp|github_pat|sk|xox[baprs])-[-_A-Za-z0-9]{10,}\b"),
    re.compile(
        r"(?i)\b(?:api[_-]?key|access[_-]?token|secret|password|authorization)\s*[:=]\s*['\"]?[^\s'\"]{8,}"
    ),
)
SECRET_KEY_PATTERN = re.compile(
    r"(?i)(?:authorization|api[_-]?key|access[_-]?token|refresh[_-]?token|password|secret)"
)
ENV_REFERENCE_PATTERN = re.compile(
    r"^\$\{[A-Z][A-Z0-9_]*\}$|^\$[A-Z][A-Z0-9_]*$|^Bearer\s+\$\{[A-Z][A-Z0-9_]*\}$",
    re.I,
)


class DuplicateJSONKey(ValueError):
    """Raised when JSON contains a duplicate object key."""


def _reject_duplicate_keys(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            raise DuplicateJSONKey(f"duplicate JSON key: {key}")
        result[key] = value
    return result


def strict_json_loads(text: str) -> Any:
    return json.loads(
        text,
        object_pairs_hook=_reject_duplicate_keys,
        parse_constant=lambda value: (_ for _ in ()).throw(
            ValueError(f"non-finite JSON value: {value}")
        ),
    )


def strict_json_load(path: Path) -> Any:
    return strict_json_loads(path.read_text(encoding="utf-8"))


def stable_json(value: Any) -> str:
    return json.dumps(value, indent=2, ensure_ascii=False, sort_keys=True) + "\n"


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sha256_file(path: Path) -> str:
    return sha256_bytes(path.read_bytes())


def make_issue(code: str, message: str, path: str | None = None) -> dict[str, str]:
    result = {"code": code, "message": message}
    if path:
        result["path"] = path
    return result


def status_from_issues(issues: Iterable[dict[str, str]]) -> str:
    return "PASS" if not list(issues) else "FAIL"


def relative_path(root: Path, path: Path) -> str:
    try:
        return path.relative_to(root).as_posix()
    except ValueError:
        return path.as_posix()


def iter_files(root: Path) -> list[Path]:
    """Return regular files below *root* in stable, portable order."""

    if not root.is_dir():
        return []
    return sorted(
        (path for path in root.rglob("*") if path.is_file()),
        key=lambda path: path.relative_to(root).as_posix().lower(),
    )


def is_env_reference(value: Any) -> bool:
    return isinstance(value, str) and bool(ENV_REFERENCE_PATTERN.fullmatch(value.strip()))


def is_link_like(path: Path) -> bool:
    try:
        if path.is_symlink() or os.path.islink(path):
            return True
        attributes = getattr(path.lstat(), "st_file_attributes", 0)
        return bool(attributes & 0x40000000)  # FILE_ATTRIBUTE_REPARSE_POINT
    except (FileNotFoundError, OSError):
        return False


def security_issues(root: Path) -> list[dict[str, str]]:
    issues: list[dict[str, str]] = []
    if is_link_like(root):
        return [make_issue("LINKED_ROOT", "plugin root must not be a symlink or reparse point")]

    try:
        paths = sorted(
            (path for path in root.rglob("*") if ".git" not in path.parts),
            key=lambda path: path.as_posix().lower(),
        )
    except OSError as exc:
        return [make_issue("SCAN_ERROR", str(exc))]

    for path in paths:
        rel = relative_path(root, path)
        if is_link_like(path):
            issues.append(make_issue("LINK_ESCAPE", "symlink or reparse point is not allowed", rel))
            continue
        if path.name == "__pycache__" or path.suffix.lower() in {".pyc", ".pyo"}:
            issues.append(make_issue("GENERATED_CACHE", "generated bytecode/cache is not package content", rel))
            continue
        lowered_name = path.name.lower()
        if any(
            lowered_name == part or lowered_name.startswith(part + ".")
            for part in SECRET_FILENAME_PARTS
        ) or path.suffix.lower() in SECRET_SUFFIXES:
            issues.append(make_issue("SECRET_FILE", "credential or private-key file is not allowed", rel))
            continue
        if not path.is_file():
            continue
        try:
            data = path.read_bytes()
        except OSError as exc:
            issues.append(make_issue("READ_ERROR", str(exc), rel))
            continue
        text = data.decode("utf-8", errors="ignore")
        for pattern in SECRET_VALUE_PATTERNS:
            if pattern.search(text):
                issues.append(make_issue("SECRET_VALUE", "secret-like value detected", rel))
                break
    return issues


def validate_name(name: Any, field: str = "name") -> list[dict[str, str]]:
    if not isinstance(name, str):
        return [make_issue("INVALID_NAME", f"{field} must be a string")]
    if not 1 <= len(name) <= 64 or not NAME_PATTERN.fullmatch(name):
        return [make_issue("INVALID_NAME", f"{field} is not valid lower-case plugin name: {name}")]
    return []


def parse_frontmatter(text: str) -> tuple[dict[str, str], str | None]:
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}, "SKILL.md must begin with YAML frontmatter"
    try:
        end = next(index for index, line in enumerate(lines[1:], start=1) if line.strip() == "---")
    except StopIteration:
        return {}, "frontmatter closing delimiter is missing"
    values: dict[str, str] = {}
    for line in lines[1:end]:
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        key, separator, value = line.partition(":")
        if not separator:
            return {}, f"invalid frontmatter line: {line}"
        values[key.strip()] = value.strip().strip('"\'')
    body = "\n".join(lines[end + 1 :]).strip()
    if not body:
        return values, "skill body must not be empty"
    return values, None


def validate_skill(skill_dir: Path, root: Path) -> list[dict[str, str]]:
    issues: list[dict[str, str]] = []
    skill_file = skill_dir / "SKILL.md"
    rel = relative_path(root, skill_file)
    if not skill_file.is_file():
        return [make_issue("MISSING_SKILL_FILE", "direct skill directory must contain SKILL.md", rel)]
    try:
        frontmatter, error = parse_frontmatter(skill_file.read_text(encoding="utf-8"))
    except OSError as exc:
        return [make_issue("READ_ERROR", str(exc), rel)]
    if error:
        issues.append(make_issue("INVALID_FRONTMATTER", error, rel))
        return issues
    expected_name = skill_dir.name
    skill_name = frontmatter.get("name")
    if skill_name != expected_name or not FRONTMATTER_NAME_PATTERN.fullmatch(skill_name or ""):
        issues.append(make_issue("INVALID_SKILL_NAME", "frontmatter name must match the skill directory", rel))
    description = frontmatter.get("description", "").strip()
    if not description:
        issues.append(make_issue("INVALID_SKILL_DESCRIPTION", "description must not be empty", rel))
    unfinished_marker = "[" + chr(84) + "ODO"
    if unfinished_marker in skill_file.read_text(encoding="utf-8"):
        issues.append(make_issue("UNFINISHED_MARKER", "skill contains an unfinished placeholder", rel))
    return issues


def validate_mcp_manifest(path: Path, root: Path) -> list[dict[str, str]]:
    issues: list[dict[str, str]] = []
    rel = relative_path(root, path)
    try:
        manifest = strict_json_load(path)
    except (OSError, ValueError) as exc:
        return [make_issue("INVALID_MCP_JSON", str(exc), rel)]
    if not isinstance(manifest, dict):
        return [make_issue("INVALID_MCP_SHAPE", "mcp.json must be an object", rel)]
    if manifest.get("$schema") != MCP_SCHEMA:
        issues.append(make_issue("MCP_SCHEMA_MISMATCH", "mcp.json must target Agent Plugins 1.0.0", rel))
    servers = manifest.get("mcpServers")
    if not isinstance(servers, dict) or not servers:
        issues.append(make_issue("MCP_SERVERS_REQUIRED", "mcpServers must be a non-empty object", rel))
        return issues
    for name, server in servers.items():
        if not isinstance(server, dict):
            issues.append(make_issue("MCP_SERVER_SHAPE", f"server {name} must be an object", rel))
            continue
        server_type = server.get("type")
        if server_type not in {"stdio", "streamable-http", "sse"}:
            issues.append(make_issue("MCP_TRANSPORT", f"unsupported transport for {name}: {server_type}", rel))
        if server_type == "stdio" and not isinstance(server.get("command"), str):
            issues.append(make_issue("MCP_COMMAND", f"stdio server {name} requires command", rel))
        if server_type in {"streamable-http", "sse"} and not isinstance(server.get("url"), str):
            issues.append(make_issue("MCP_URL", f"HTTP server {name} requires url", rel))
        for container_key in ("env", "headers"):
            container = server.get(container_key, {})
            if not isinstance(container, dict):
                issues.append(make_issue("MCP_CONTAINER", f"{container_key} must be an object", rel))
                continue
            for key, value in container.items():
                if is_env_reference(value):
                    continue
                if SECRET_KEY_PATTERN.search(str(key)) or any(pattern.search(str(value)) for pattern in SECRET_VALUE_PATTERNS):
                    issues.append(make_issue("MCP_SECRET", f"credential-bearing {container_key} is not allowed: {key}", rel))
    return issues


def validate_portable(root: Path) -> tuple[dict[str, Any], list[dict[str, str]]]:
    issues: list[dict[str, str]] = []
    if is_link_like(root):
        return {"status": "FAIL", "checks": {"manifest": "FAIL", "skills": "FAIL", "security": "FAIL"}, "skill_count": 0}, [
            make_issue("LINKED_ROOT", "plugin root must not be a symlink or reparse point")
        ]
    root = root.resolve()
    if not root.is_dir():
        return {"status": "FAIL", "checks": []}, [make_issue("MISSING_ROOT", "plugin root does not exist")]

    manifest_path = root / "plugin.json"
    if not manifest_path.is_file():
        issues.append(make_issue("MISSING_MANIFEST", "portable root plugin.json is required", "plugin.json"))
        manifest: dict[str, Any] = {}
    else:
        try:
            manifest = strict_json_load(manifest_path)
        except (OSError, ValueError) as exc:
            manifest = {}
            issues.append(make_issue("INVALID_MANIFEST_JSON", str(exc), "plugin.json"))

    if not isinstance(manifest, dict):
        issues.append(make_issue("INVALID_MANIFEST_SHAPE", "plugin.json must be an object", "plugin.json"))
        manifest = {}
    issues.extend(validate_name(manifest.get("name")))
    if manifest.get("$schema") != PORTABLE_SCHEMA:
        issues.append(make_issue("SCHEMA_MISMATCH", "portable manifest must target Agent Plugins 1.0.0", "plugin.json"))
    for key in manifest:
        if key in FORBIDDEN_PORTABLE_FIELDS:
            issues.append(make_issue("NATIVE_FIELD_IN_PORTABLE", f"native field is not portable: {key}", "plugin.json"))
        elif key not in PORTABLE_FIELDS:
            issues.append(make_issue("UNKNOWN_PORTABLE_FIELD", f"unsupported portable field: {key}", "plugin.json"))
    if "version" in manifest and not isinstance(manifest["version"], str):
        issues.append(make_issue("INVALID_VERSION", "version must be a string", "plugin.json"))
    if "description" in manifest and not isinstance(manifest["description"], str):
        issues.append(make_issue("INVALID_DESCRIPTION", "description must be a string", "plugin.json"))
    if "author" in manifest and (
        not isinstance(manifest["author"], dict)
        or any(key not in {"name", "email", "url"} for key in manifest["author"])
    ):
        issues.append(make_issue("INVALID_AUTHOR", "author must contain only name, email, and url", "plugin.json"))

    skills_root = root / "skills"
    skill_dirs: list[Path] = []
    if not skills_root.is_dir():
        issues.append(make_issue("MISSING_SKILLS", "portable package requires a skills directory", "skills"))
    else:
        for child in sorted(skills_root.iterdir(), key=lambda path: path.name.lower()):
            if child.is_dir() and not is_link_like(child):
                skill_dirs.append(child)
            elif child.is_file():
                issues.append(make_issue("SKILL_LAYOUT", "skills must contain immediate skill directories", relative_path(root, child)))
    if not skill_dirs:
        issues.append(make_issue("NO_SKILLS", "portable package requires at least one skill", "skills"))
    for skill_dir in skill_dirs:
        issues.extend(validate_skill(skill_dir, root))

    mcp_path = root / "mcp.json"
    if mcp_path.exists():
        issues.extend(validate_mcp_manifest(mcp_path, root))

    issues.extend(security_issues(root))
    report = {
        "status": status_from_issues(issues),
        "checks": {
            "manifest": "PASS" if manifest_path.is_file() and not any(item["code"] in {"MISSING_MANIFEST", "INVALID_MANIFEST_JSON"} for item in issues) else "FAIL",
            "skills": "PASS" if skill_dirs and not any(item["code"] in {"MISSING_SKILLS", "NO_SKILLS", "MISSING_SKILL_FILE", "INVALID_FRONTMATTER"} for item in issues) else "FAIL",
            "security": "PASS" if not any(item["code"] in {"SECRET_FILE", "SECRET_VALUE", "LINK_ESCAPE", "GENERATED_CACHE", "MCP_SECRET"} for item in issues) else "FAIL",
        },
        "skill_count": len(skill_dirs),
    }
    return report, issues
